In [8]:
for i in range(6):
    if(i%2!=0):
        for i in range(i):
            print('*',end=" ")

* * * * * * * * * 

In [ ]:
'''
What is numpy ?
Numpy is fundamental packages for scientific computation in python. Mathematical, Logical, Shape Manipulation, sorting, 
Selection, I/O, Discrete fourier transform, basic statistical operation, basic linear algebra
'''

In [2]:
import numpy as np

In [10]:
print(np.__version__)

1.23.5


In [11]:
ar = np.array([1,2,3])
print(ar)

[1 2 3]


In [12]:
print(type(ar))

<class 'numpy.ndarray'>


In [3]:
ar1 = np.array([[1,2,3],[4,5,6]])
print(ar1)

[[1 2 3]
 [4 5 6]]


In [4]:
ar2 = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(ar2)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [5]:
ar3 = np.array([1,2,3],dtype=float)
print(ar3)

[1. 2. 3.]


In [7]:
a = np.arange(1,11,2)   #ARANGE
print(a)

[1 3 5 7 9]


In [8]:
ad = np.arange(16).reshape(2,2,2,2)    #RESHAPE
print(ad)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [9]:
ad = np.arange(16).reshape(4,4)
print(ad)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [11]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])