In [1]:
#W.A.P to print (Hello) using string Allocate string to a variable
a = input("Enter your string")
print(a)

Enter your stringHello
Hello


In [3]:
print(type(a))

<class 'str'>


In [6]:
#W.A.P to print String using three quotes
str1 = '''Hello'''
str2 = ''' I am '''
str3 = '''Jeet'''
a = str1+str2+str3
print(a)

Hello I am Jeet


In [8]:
#W.A.P to access the 1st position character using index value.
b = input("enter your string : ")
a = input("Which character index u want : ")
print(b.rfind(a))

enter your string : jeet
Which character index u want : e
2


In [9]:
# How to get common items between two numpy arrays
import numpy as np

In [10]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [11]:
b = np.array([1,2,3,5,4,7])
print(b)

[1 2 3 5 4 7]


In [12]:
np.intersect1d(a,b)

array([1, 2, 3, 4])

In [13]:
np.setdiff1d(a,b)

array([], dtype=int32)

In [14]:
#how to get the position where elements of two array match

In [23]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,2,3,4,5,7,8,9,1])

In [24]:
np.where(a== b)

(array([0, 1, 2, 3, 4], dtype=int64),)

In [12]:
#W.A.P to Access the string after the index value 1 Slicing
b = input("enter your string : ")
print(b[1:])

enter your string : jeetdesai
eetdesai


In [13]:
#W.A.P to Access the string before the index value 5
b = input("enter your string : ")
print(b[:5])

enter your string : jeetdesai
jeetd


In [14]:
#W.A.P to Access the String between the index value 1 to 4
b = input("enter your string : ")
print(b[1:4])

enter your string : jeetdesai
eet


In [33]:
# W.A.P to print the string from the last index value
b = input("enter your string : ")
print(b[-1])

enter your string : jeet
t


In [36]:
# W.A.P to print the String alternate character after the index value 1
b = input("enter your string : ")
a = (b[3])
c = 'p'
d = b.replace(a,c)
print(d)

enter your string : jeet
jeep


In [38]:
#W.A.P create the list of multiple datatype element
a=[1,"jeet",5.2,True]
print(type(a))
print(a)

<class 'list'>
[1, 'jeet', 5.2, True]


In [39]:
#W.A.P to find the length of the list.
print(len(a))

4


In [40]:
#W.A.P to update the list using the insert() and append()
a.append("Hello world")
print(a)

[1, 'jeet', 5.2, True, 'Hello world']


In [49]:
a.insert(0,"python")
print(a)

['python', 1, 'jeet', 5.2, True]


In [42]:
#W.A.P to remove the element using the pop() and remove()
a.pop()
print(a)

['python', 1, 'jeet', 5.2, True]


In [51]:
a.remove("python")

In [52]:
print(a)

[1, 'jeet', 5.2, True]


In [53]:
#W.A.P to access value on index value in the list
a

[1, 'jeet', 5.2, True]

In [59]:
print(list(enumerate(a)))

[(0, 1), (1, 'jeet'), (2, 5.2), (3, True)]


In [62]:
#W.A.P to access the value after the index value 1.
print(a[1:])

['jeet', 5.2, True]


In [63]:
#W.A.P to access the value between 1 to 5
print(a[1:6])

['jeet', 5.2, True]


In [64]:
a.append("Hello")

In [65]:
a.append("desai")

In [66]:
a

[1, 'jeet', 5.2, True, 'Hello', 'desai']

In [67]:
a.append(21)

In [68]:
a.append(12)

In [69]:
a

[1, 'jeet', 5.2, True, 'Hello', 'desai', 21, 12]

In [70]:
print(a[1:6])

['jeet', 5.2, True, 'Hello', 'desai']


In [71]:
# W.A.P to access the value till index 5
print(a[:5])

[1, 'jeet', 5.2, True, 'Hello']


In [72]:
#W.A.P to update the list using the index value
a

[1, 'jeet', 5.2, True, 'Hello', 'desai', 21, 12]

In [ ]:
b = int(input("Enter the index value which you want to update : "))
